// <auto-generated />
using System;
using AMSAReportingSystem.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AMSAReportingSystem.Migrations
{
    [DbContext(typeof(AMSAReportingDbContext))]
    [Migration("20260513111813_AddStateAggregationMetadata")]
    partial class AddStateAggregationMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.DepartmentReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AttendanceCount")
                        .HasColumnType("int");

                    b.Property<int?>("BeneficiaryCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CycleId")
                        .HasColumnType("int");

                    b.Property<int>("Department")
                        .HasColumnType("int");

                    b.Property<decimal?>("DuesCollected")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ExpectedDues")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("HasOnCampusActivity")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSubmitted")
                        .HasColumnType("bit");

                    b.Property<int?>("MemberParticipantCount")
                        .HasColumnType("int");

                    b.Property<int?>("ProgramCount")
                        .HasColumnType("int");

                    b.Property<string>("ReportData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.Property<int?>("SessionsOrganized")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubmittedByMemberId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalMemberCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("ReportId");

                    b.HasIndex("ReportId", "Department")
                        .IsUnique();

                    b.ToTable("DepartmentReports");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedByNationalAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AcknowledgedByNationalMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedByPresidentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByPresidentMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedByStateAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByStateMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCompliant")
                        .HasColumnType("bit");

                    b.Property<string>("NationalNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PresidentialNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<string>("StateNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SubmittedByMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedToPresidentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("StateId");

                    b.HasIndex("Status");

                    b.HasIndex("UnitId");

                    b.HasIndex("UnitId", "CycleId")
                        .IsUnique();

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.ReportActivityLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("ActionAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActionByMemberId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReportId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportId");

                    b.ToTable("ReportActivityLogs");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.ReportingCycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CycleMonth")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReminderSentAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SubmissionDeadline")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CycleMonth")
                        .IsUnique();

                    b.ToTable("ReportingCycles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CycleMonth = "January 2025",
                            EndDate = new DateTime(2025, 1, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsLocked = false,
                            StartDate = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SubmissionDeadline = new DateTime(2025, 2, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UpdatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.StateReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AcknowledgedByNationalAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AcknowledgedByNationalMemberId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ApprovedByPresidentAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("ApprovedByPresidentMemberId")
                        .HasColumnType("int");

                    b.Property<string>("ChallengesFaced")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CycleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsAggregated")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAggregatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastAggregatedByMemberId")
                        .HasColumnType("int");

                    b.Property<string>("NationalNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalSupportNeeded")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OtherNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PresidentialNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SubmittedByMemberId")
                        .HasColumnType("int");

                    b.Property<int>("TotalUnitReportsCount")
                        .HasColumnType("int");

                    b.Property<string>("UnitImprovementPlan")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int?>("UnitPerformanceRating")
                        .HasColumnType("int");

                    b.Property<int>("UnitsAttendedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CycleId");

                    b.HasIndex("StateId");

                    b.HasIndex("Status");

                    b.HasIndex("StateId", "CycleId")
                        .IsUnique();

                    b.ToTable("StateReports");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.StateReportProgram", b =>
                {
                    b.Property<int>("ProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgramId"));

                    b.Property<bool>("IsAutoAggregated")
                        .HasColumnType("bit");

                    b.Property<string>("Objectives")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Outcomes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("StateReportId")
                        .HasColumnType("int");

                    b.Property<int?>("TotalAttendance")
                        .HasColumnType("int");

                    b.Property<int?>("TotalBeneficiaries")
                        .HasColumnType("int");

                    b.HasKey("ProgramId");

                    b.HasIndex("StateReportId");

                    b.ToTable("StateReportPrograms");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.DepartmentReport", b =>
                {
                    b.HasOne("AMSAReportingSystem.Data.Entities.Report", "Report")
                        .WithMany("DepartmentReports")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.Report", b =>
                {
                    b.HasOne("AMSAReportingSystem.Data.Entities.ReportingCycle", "Cycle")
                        .WithMany("Reports")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.ReportActivityLog", b =>
                {
                    b.HasOne("AMSAReportingSystem.Data.Entities.Report", "Report")
                        .WithMany("ActivityLogs")
                        .HasForeignKey("ReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Report");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.StateReport", b =>
                {
                    b.HasOne("AMSAReportingSystem.Data.Entities.ReportingCycle", "Cycle")
                        .WithMany("StateReports")
                        .HasForeignKey("CycleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cycle");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.StateReportProgram", b =>
                {
                    b.HasOne("AMSAReportingSystem.Data.Entities.StateReport", "StateReport")
                        .WithMany("Programs")
                        .HasForeignKey("StateReportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StateReport");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.Report", b =>
                {
                    b.Navigation("ActivityLogs");

                    b.Navigation("DepartmentReports");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.ReportingCycle", b =>
                {
                    b.Navigation("Reports");

                    b.Navigation("StateReports");
                });

            modelBuilder.Entity("AMSAReportingSystem.Data.Entities.StateReport", b =>
                {
                    b.Navigation("Programs");
                });
#pragma warning restore 612, 618
        }
    }
}
